### ISSUE TITLE
[Bug]: Sheet - Unable to locate a class or view for component [lucide-x].

### ISSUE THREAD

**Issue by sugith** [luvi-ui/laravel-luvi#11]
### What happened?

Adding a sheet gives you an error "Unable to locate a class or view for component [lucide-x]."

### How to reproduce the bug

<x-sheet>
        <x-sheet.trigger>open</x-sheet.trigger>
        <x-sheet.content>
            <x-sheet.header>
                <x-sheet.title>are you absolutely sure?</x-sheet.title>
                <x-sheet.description>
                    this action cannot be undone. this will permanently delete your account
                    and remove your data from our servers.
                </x-sheet.description>
            </x-sheet.header>
        </x-sheet.content>
    </x-sheet>

### Package Version

0.4.4

### PHP Version

8.3.12

### Laravel Version

11.9

**Comment by anotherfrontendguy** [comment]
Hey ✌️
oh I see. This error occurs because the lucide icon set is not installed. We listed this as optional in the installation guide but I think we should change this to a requirement. Thanks for pointing that out. 

The solution for the problem should be to install the icon set:

```shell
composer require mallardduck/blade-lucide-icons
```
