### ISSUE TITLE
[Bug]: Class "App\Services\ButtonCvaService" not found

### ISSUE THREAD

**Issue by fachrel** [luvi-ui/laravel-luvi#6]
### What happened?

When i try to publish button (or any components that have Service class) it gives me this error on terminal.
` ERROR  Can't locate path: <vendor/luvi-ui/laravel-luvi/src/../App/Services/ButtonCvaService.php>.  `

### How to reproduce the bug

php artisan vendor:publish --tag=button --force

### Package Version

0.4.0

### PHP Version

8.2.19

### Laravel Version

11.0

### Which operating systems does this happen with?

Linux

**Comment by anotherfrontendguy** [comment]
Thank you for reporting!

This seems to be an issue with case-sensitive file systems. We just released a hotfix which addresses this problem. Could you please update the package to `0.4.1` and test it again?

**Comment by fachrel** [comment]
Thank you for fixing it.

I updated the package to `0.4.1` and have tested it, it works now.

**Comment by anotherfrontendguy** [comment]
Glad to hear 👍 

Closing this issue (fixed by 78ec0f9609b1077e5cd782b4658fef43d749aa3a)
